import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideHeader from "./components/sideHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid h-screen relative">
          <SideHeader />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
